# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xcku115-flva2104-3-e

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /nethome/wsutton8/ECE6276/ECE6276/HW4/lab_4/run/vivado_run/mac_pipelined/mac_pipelined.cache/wt [current_project]
set_property parent.project_path /nethome/wsutton8/ECE6276/ECE6276/HW4/lab_4/run/vivado_run/mac_pipelined/mac_pipelined.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  /nethome/wsutton8/ECE6276/ECE6276/HW4/lab_4/src/stage1.vhd
  /nethome/wsutton8/ECE6276/ECE6276/HW4/lab_4/src/mac_updated.vhd
  /nethome/wsutton8/ECE6276/ECE6276/HW4/lab_4/src/stage3.vhd
  /nethome/wsutton8/ECE6276/ECE6276/HW4/lab_4/src/stage2.vhd
  /nethome/wsutton8/ECE6276/ECE6276/HW4/lab_4/src/processor_top.vhd
}
read_xdc /nethome/wsutton8/ECE6276/ECE6276/HW4/constraints_lab4.xdc
set_property used_in_implementation false [get_files /nethome/wsutton8/ECE6276/ECE6276/HW4/constraints_lab4.xdc]

synth_design -top processor_top -part xcku115-flva2104-3-e
write_checkpoint -noxdef processor_top.dcp
catch { report_utilization -file processor_top_utilization_synth.rpt -pb processor_top_utilization_synth.pb }
